//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AopAttributeCalculatorClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TestModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceTestSoap")]
    public interface WebServiceTestSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 test 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AopAttributeCalculatorClient.ServiceReference1.HelloWorldResponse HelloWorld(AopAttributeCalculatorClient.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorld1Result 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld1", ReplyAction="*")]
        AopAttributeCalculatorClient.ServiceReference1.HelloWorld1Response HelloWorld1(AopAttributeCalculatorClient.ServiceReference1.HelloWorld1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AopAttributeCalculatorClient.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AopAttributeCalculatorClient.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AopAttributeCalculatorClient.ServiceReference1.TestModel test;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(AopAttributeCalculatorClient.ServiceReference1.TestModel test) {
            this.test = test;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AopAttributeCalculatorClient.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AopAttributeCalculatorClient.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AopAttributeCalculatorClient.ServiceReference1.TestModel[] HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(AopAttributeCalculatorClient.ServiceReference1.TestModel[] HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld1", Namespace="http://tempuri.org/", Order=0)]
        public AopAttributeCalculatorClient.ServiceReference1.HelloWorld1RequestBody Body;
        
        public HelloWorld1Request() {
        }
        
        public HelloWorld1Request(AopAttributeCalculatorClient.ServiceReference1.HelloWorld1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorld1RequestBody {
        
        public HelloWorld1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld1Response", Namespace="http://tempuri.org/", Order=0)]
        public AopAttributeCalculatorClient.ServiceReference1.HelloWorld1ResponseBody Body;
        
        public HelloWorld1Response() {
        }
        
        public HelloWorld1Response(AopAttributeCalculatorClient.ServiceReference1.HelloWorld1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorld1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorld1Result;
        
        public HelloWorld1ResponseBody() {
        }
        
        public HelloWorld1ResponseBody(string HelloWorld1Result) {
            this.HelloWorld1Result = HelloWorld1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTestSoapChannel : AopAttributeCalculatorClient.ServiceReference1.WebServiceTestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTestSoapClient : System.ServiceModel.ClientBase<AopAttributeCalculatorClient.ServiceReference1.WebServiceTestSoap>, AopAttributeCalculatorClient.ServiceReference1.WebServiceTestSoap {
        
        public WebServiceTestSoapClient() {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AopAttributeCalculatorClient.ServiceReference1.HelloWorldResponse AopAttributeCalculatorClient.ServiceReference1.WebServiceTestSoap.HelloWorld(AopAttributeCalculatorClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public AopAttributeCalculatorClient.ServiceReference1.TestModel[] HelloWorld(AopAttributeCalculatorClient.ServiceReference1.TestModel test) {
            AopAttributeCalculatorClient.ServiceReference1.HelloWorldRequest inValue = new AopAttributeCalculatorClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new AopAttributeCalculatorClient.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.test = test;
            AopAttributeCalculatorClient.ServiceReference1.HelloWorldResponse retVal = ((AopAttributeCalculatorClient.ServiceReference1.WebServiceTestSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AopAttributeCalculatorClient.ServiceReference1.HelloWorld1Response AopAttributeCalculatorClient.ServiceReference1.WebServiceTestSoap.HelloWorld1(AopAttributeCalculatorClient.ServiceReference1.HelloWorld1Request request) {
            return base.Channel.HelloWorld1(request);
        }
        
        public string HelloWorld1() {
            AopAttributeCalculatorClient.ServiceReference1.HelloWorld1Request inValue = new AopAttributeCalculatorClient.ServiceReference1.HelloWorld1Request();
            inValue.Body = new AopAttributeCalculatorClient.ServiceReference1.HelloWorld1RequestBody();
            AopAttributeCalculatorClient.ServiceReference1.HelloWorld1Response retVal = ((AopAttributeCalculatorClient.ServiceReference1.WebServiceTestSoap)(this)).HelloWorld1(inValue);
            return retVal.Body.HelloWorld1Result;
        }
    }
}
